### ISSUE TITLE
include data used by pranaydeeps/Ancient-Greek-BERT

### ISSUE THREAD

**Issue by jankounchained** [centre-for-humanities-computing/homerCy#1]
### Gorma's treebank
https://github.com/rgorman/Greek_Dependency_Treebanks

This is a treebank.
Most of the observations are already included in perseus & proiel (alegedly)

### First1KGreek
https://github.com/OpenGreekAndLatin/First1KGreek

This is actually a corpus.
Marton has a parser for it.

**Comment by x-tabdeveloping** [comment]
The treebanks are included in the universal dependency treebanks, First1KGreek is already parsed by preprocessing scripts
